### ISSUE TITLE
Game does not run on Arch Linux

### ISSUE THREAD

**Issue by SanskritFritz** [darealshinji/polly-b-gone#1]
Hi. How do I build this version on archlinux?

Another question, I hope you can help me, my version builds though but it doesn't run:

```
libpng warning: iCCP: known incorrect sRGB profile
fish: “./polly-b-gone” terminated by signal SIGSEGV (Address boundary error)
```

Can you please help me, I don't know much about autotools or debugging.

**Comment by darealshinji** [comment]
Building with autotools should be easy: `autoreconf -if && ./configure && make`

A quick search reveals that libpng-1.6 (which Arch is probably using) is very strict about PNG files with wrong profiles: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile

polly-b-gone or SDL-Image probably treats the warning as an error. Can you try to use pngcrush to edit `resources/title.png` (the only PNG file used) and see if that fixes it?
```
pngcrush -ow -rem allb -reduce resources/title.png
```

**Comment by SanskritFritz** [comment]
Thanks for your reply.
Now I was able to compile yours too, but pngcrush didn't help either (although the warning is gone):
```
frank@HomeC ~/B/a/S/p/polly-b-gone> ./polly-b-gone 
loading game files from: resources/
fish: “./polly-b-gone” terminated by signal SIGSEGV (Address boundary error)
```
A black screen appears for a fraction of a second.

**Comment by darealshinji** [comment]
Weird. I have no problems, tested it with gcc 5, 6 and 7.
Does it make a difference whether you build it with `./configure --with-glew` or just with `./configure`?

**Comment by SanskritFritz** [comment]
I found something!
strace reveals this:
```error while loading shared libraries: libGLEW.so.2.0: cannot open shared object file: No such file or directory```

But locate libGLEW.so produces
```
/usr/lib/libGLEW.so
/usr/lib/libGLEW.so.2.1
/usr/lib/libGLEW.so.2.1.0
```

**Comment by darealshinji** [comment]
Doesn't `/usr/lib/libGLEW.so` point to `/usr/lib/libGLEW.so.2.1`?

**Comment by SanskritFritz** [comment]
It does.
```
frank@HomeC ~> ll /usr/lib/libGLEW.so
lrwxrwxrwx 1 root root 16 2017-08-03 18:29 /usr/lib/libGLEW.so -> libGLEW.so.2.1.0
```
I tried this:
```
root@HomeC ~# ln -s /usr/lib/libGLEW.so.2.1 /usr/lib/libGLEW.so.2.0
root@HomeC ~# ln -s /usr/lib/libGLEW.so.2.1.0  /usr/lib/libGLEW.so.2.0.0
```
Now strace shows this:
```
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/bash.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
fstat(2, {st_mode=S_IFCHR|0600, st_rdev=makedev(136, 2), ...}) = 0
open("/usr/share/locale/en_US.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en_US/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.UTF-8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en.utf8/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/usr/share/locale/en/LC_MESSAGES/libc.mo", O_RDONLY) = -1 ENOENT (No such file or directory)
write(2, "/usr/bin/polly-b-gone: line 2:  "..., 90/usr/bin/polly-b-gone: line 2:  2313 Segmentation fault      (core dumped) ./polly-b-gone
```

**Comment by darealshinji** [comment]
I'll try it myself on Arch Linux in VirtualBox, but right now I'm experiencing some Internet connection issues, so it might take a while.

**Comment by darealshinji** [comment]
I can compile it on Antergos but when I run it I'm getting a segmentation fault, with and without glew. I'm getting the same with the pre-built version from the release section. I really don't know what to do about it, it runs fine on Ubuntu. Maybe it's an issue with SDL or another dependency?

**Comment by SanskritFritz** [comment]
Oh boy, oh boy. I have no idea how to proceed now. 😞

**Comment by darealshinji** [comment]
You could try to build the SDL libraries from source and use those to build the game. I could also try to build an AppImage and see if that runs.

**Comment by darealshinji** [comment]
Did a little debugging: it seems to crash when it runs the first libglut function after `glutInit`. I've downloaded libglut from Ubuntu and added it to LD_LIBRARY_PATH, but the same happened. Maybe there's something wrong with how the libglut functions are used in the code or maybe it's something else about using OpenGL on Arch.

**Comment by SanskritFritz** [comment]
Well, about half a year ago it worked flawlessly on archlinux. Some new versions of libs could have done this.

**Comment by darealshinji** [comment]
Here are AppImages: [GPL](https://drive.google.com/file/d/0BxClEVSW8QykbkNOVDNlMDlEaUE/view?usp=sharing) | [non-free](https://drive.google.com/file/d/0BxClEVSW8QykV193RTNWelVNa0U/view?usp=sharing)

But they crash on Antergos for me. If they don't work on your system, maybe you find someone from the Arch Linux community who can figure out the issue and how to fix it.

**Comment by SanskritFritz** [comment]
Whohoo, this one works here flawlessly, even with sound! Thanks for this. Now I have to dig into appimages, it looks great. I used the AUR appimage-git package.

**Comment by darealshinji** [comment]
Good to hear that it works. I will upload them to the release section. I don't think you need the package `appimage-git`, which is intended to build AppImages. To run them you only need fuse/libfuse.

I will keep this bug report open since the original crash issue still isn't solved.

**Comment by SanskritFritz** [comment]
Thanks and you're right, the appimage-git package is not needed.

**Comment by SanskritFritz** [comment]
Sadly the appimage doesn't work either now :cry: 
Can we somehow dig into that? I'm ready to help if I can.

**Comment by IslandC0der** [comment]
I'm glad to help too!
I've compiled both of your forks, neither of them run on my arch system (segmentation fault). Same for the AppImages. Let me know if you need some strace debugging.

**Comment by darealshinji** [comment]
Still working for me on Ubuntu, strange. I opened a new branch where I've added only a limited number of changes to make it compile on Linux (and eliminate warnings), ignoring compat for Windows and Mac: https://github.com/darealshinji/polly-b-gone/tree/linux-new

Try to build and run the game: `make -j4 && ./polly-b-gone`

If it still doesn't run try it again with GLUT disabled:
```
make clean
make -j4 DISABLE_GLUT=1
./polly-b-gone
```

**Comment by IslandC0der** [comment]
Hey, it works when compiling from that branch with GLUT disabled! :smiley: 
Though that old warning is back: <code>libpng warning: iCCP: known incorrect sRGB profile</code>.

**Comment by IslandC0der** [comment]
UPDATE: got rid of the warning by doing this:

> A quick search reveals that libpng-1.6 (which Arch is probably using) is very strict about PNG files with wrong profiles: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile
> 
> polly-b-gone or SDL-Image probably treats the warning as an error. Can you try to use pngcrush to edit `resources/title.png` (the only PNG file used) and see if that fixes it?
> 
> ```
> pngcrush -ow -rem allb -reduce resources/title.png
> ```

**Comment by darealshinji** [comment]
Be warned though that Polly looks different with GLUT disabled.

**Comment by SanskritFritz** [comment]
Disabling GLUT at least enables us to play the game! Thanks. Polly looks indeed strange...
So we have to look for the problem in Glut?

**Comment by SanskritFritz** [comment]
Here is a strace output:
https://gist.github.com/SanskritFritz/0e08f8eedeefce72fcefae01d8ebd1ad

**Comment by IslandC0der** [comment]
Yeah, Polly itself looks odd, but the rest of the game seems normal (at least compared to some screenshots I found online). Thank you so much @darealshinji!

**Comment by darealshinji** [comment]
The strace actually helped! This issue doesn't happend if you guys install the proprietary nvidia drivers instead of the "nouveau" drivers. So it's not exactly related to Arch.

**Comment by darealshinji** [comment]
libglut can now be disabled through `configure`

**Comment by SanskritFritz** [comment]
I installed the proprietary nvidia-dkms package, but that didn't help sadly. Here is the strace of that run: https://gist.github.com/SanskritFritz/2ce90523f6db024bab148fa783b04e1f

**Comment by darealshinji** [comment]
Hmm, I don't know how to help otherwise, sorry. Maybe you should make a bug report to the Arch Linux package maintainers of freeglut and see what they say?

**Comment by SanskritFritz** [comment]
I assume you're using freeglut in Ubuntu. Could you try with freeglut3? That is what archlinux installs, same version.

**Comment by IslandC0der** [comment]
Hmm, I'm not using nouveau, I have mesa for my intel GPU and the proprietary drivers for my nvidia one.

**Comment by IslandC0der** [comment]
I've just switched to my Nvidia GPU to test, and indeed it still happens :/

**Comment by SanskritFritz** [comment]
Me too, I was with mesa. I tried with nouveau and nvidia as well.

**Comment by IslandC0der** [comment]
Update: I've just tested with the packages <code>freeglut-x11-svn</code> and <code>lib32-freeglut</code>, still no luck.

**Comment by darealshinji** [comment]
@SanskritFritz it is apparently freeglut3 I've installed: https://packages.ubuntu.com/search?keywords=freeglut
libglut.so.3 is the binary

Update: I had to add `glutinit()` to make it work on Linux. Maybe something else from the glut API needs to be added. You could also try to implement the glut calls in the game as pure GL calls based on the freeglut source code.

**Comment by SanskritFritz** [comment]
I thought I'd compare the arch and ubuntu packages how those are built. To my surprise I found that the ubuntu freeglut3 package is still at [version 2.8.1-3](https://packages.ubuntu.com/eoan/freeglut3) while the archlinux package is at [version 3.2.1-1](https://www.archlinux.org/packages/extra/x86_64/freeglut/). Is this correct? Because then there is a huge difference in the freeglut versions.

**Comment by IslandC0der** [comment]
> I thought I'd compare the arch and ubuntu packages how those are built. To my surprise I found that the ubuntu freeglut3 package is still at [version 2.8.1-3](https://packages.ubuntu.com/eoan/freeglut3) while the archlinux package is at [version 3.2.1-1](https://www.archlinux.org/packages/extra/x86_64/freeglut/). Is this correct? Because then there is a huge difference in the freeglut versions.

Damn, that version was released on April 5, 2013.
Here's what I'll do: I'll change my pacman mirrors to the archlinux archive from 2013, downgrade freeglut, and give it a shot.

**Comment by IslandC0der** [comment]
Yay, it works!!

**Comment by IslandC0der** [comment]
@SanskritFritz Try this:
At the beggining of your <code>/etc/pacman.d/mirrorlist</code> file, add <code>Server = https://archive.archlinux.org/repos/2013/08/31/$repo/os/$arch</code>
Then do <code>sudo pacman -Syy freeglut</code>
Then add <code>IgnorePkg = freeglut</code>to the <code>[options]</code> section of your <code>/etc/pacman.conf</code> file.
Remove the archive mirror.
Do <code>sudo pacman -Sy</code>
Recompile & run.

**Comment by darealshinji** [comment]
We're getting somewhere! I'll see if I can get it to work with the newer freeglut version. By the way, instead of downgrading your freeglut library system-wide you could also just extract the library from the Debian package, put it next to the game binary and start the game with `LD_LIBRARY_PATH` or `LD_PRELOAD` set and see if that works:
``` sh
LD_LIBRARY_PATH="$PWD:$LD_LIBRARY_PATH" ./polly-b-gone
LD_PRELOAD=./libglut.so.3 ./polly-b-gone
```

**Comment by IslandC0der** [comment]
> We're getting somewhere! I'll see if I can get it to work with the newer freeglut version. By the way, instead of downgrading your freeglut library system-wide you could also just extract the library from the Debian package, put it next to the game binary and start the game with `LD_LIBRARY_PATH` or `LD_PRELOAD` set and see if that works:
> 
> ```shell
> LD_LIBRARY_PATH="$PWD:$LD_LIBRARY_PATH" ./polly-b-gone
> LD_PRELOAD=./libglut.so.3 ./polly-b-gone
> ```

Can confirm that this works too. :+1:

**Comment by darealshinji** [comment]
Body and tires are now drawn even if libglut was disabled. The tire width is smaller though, still need to figure out how to change that.

**Comment by SanskritFritz** [comment]
We got momentum :smile: 
If all else fails I can create a package with freeglut2 included.

**Comment by darealshinji** [comment]
Made some tweaks and I think Polly now looks pretty much the same with and without libglut.
I have changed configure.ac so you must enable glut explicitly with `./configure --with-gut` if you really want it.

**Comment by SanskritFritz** [comment]
How do I compile that?
```make: *** No targets specified and no makefile found.  Stop.```

**Comment by darealshinji** [comment]
@SanskritFritz 
``` sh
autoreconf -if
./configure
make
```

**Comment by SanskritFritz** [comment]
Thanks! Looks great! I [updated](https://aur.archlinux.org/packages/polly-b-gone-git/) the package as well.

**Comment by SanskritFritz** [comment]
I think we can close this issue now, thanks @darealshinji for your help and for this very valuable fork.

Maybe a new release would not hurt? :smile:
